"""Runtime boundary implemented by MT5 and by test/backtest doubles."""

from __future__ import annotations

from typing import Protocol

from .models import AccountSnapshot, Candle, Direction, OrderRequest, OrderResult, Position, SymbolSpec


class Broker(Protocol):
    async def connect(self) -> None: ...
    async def close(self) -> None: ...
    async def available_symbols(self) -> tuple[str, ...]: ...
    async def candles(self, symbol: str, timeframe: str, count: int) -> list[Candle]: ...
    async def latest_tick_time(self, symbol: str) -> int: ...
    async def account(self) -> AccountSnapshot: ...
    async def positions(self) -> tuple[Position, ...]: ...
    async def symbol_spec(self, symbol: str) -> SymbolSpec: ...
    async def validate_symbol(
        self,
        symbol: str,
        direction: Direction | None = None,
        canonical_symbol: str | None = None,
    ) -> tuple[bool, str]: ...
    async def prepare_order_levels(
        self, symbol: str, direction: Direction, stop_loss: float, take_profit: float, reward_risk: float
    ) -> tuple[float, float, float]: ...
    async def volume_for_risk(
        self, symbol: str, direction: Direction, entry: float, stop_loss: float, risk_amount: float
    ) -> float: ...
    async def margin_required(self, symbol: str, direction: Direction, volume: float, price: float) -> float: ...
    async def submit(self, request: OrderRequest) -> OrderResult: ...
    async def update_stops(self, ticket: int, symbol: str, stop_loss: float, take_profit: float) -> OrderResult: ...
    def set_symbol_mapping(self, mapping: dict[str, str]) -> None: ...
